//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhGiaInDAL.RepoTinhGia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAN_GAP
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<decimal> BHR { get; set; }
        public Nullable<int> Toc_do_con { get; set; }
        public Nullable<double> Thoi_gian_chuan_bi { get; set; }
        public string Day_so_luong { get; set; }
        public string Day_loi_nhuan { get; set; }
        public Nullable<int> Thu_tu { get; set; }
    }
}
